name: Trigger auto deployment for swiftfiddle-runner-functions-533

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "**"
      - ".github/workflows/swiftfiddle-runner-functions-533-AutoDeployTrigger-95c15ce6-ebae-4bf0-afba-7cf7e3f6bc3a.yml"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS533_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS533_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS533_REGISTRY_PASSWORD }}
          containerAppName: swiftfiddle-runner-functions-533
          resourceGroup: swiftfiddle
          imageToBuild: swiftfiddle/swiftfiddle-runner-functions-533:latest
